
variables:
  build_num: $(Build.BuildNumber)
  
jobs:
- job: PyPi_Linux
  pool:
   vmImage: 'ubuntu-18.04'
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
    
  - script: |
      sudo apt-get install zlib1g-dev
      echo "Which Conda: `which conda`"
      conda create --yes --name BuildEnv
      source activate BuildEnv
      echo "Conda: `which conda`"
      echo "Conda version: `conda --version`"
      python -m pip install wheel twine ivpm
    displayName: 'Install wheel+twine+ivpm'
    
  - script: |
      source activate BuildEnv
      conda install -y -c timvideos --name BuildEnv verilator
      conda install -y -c anaconda  --name BuildEnv zlib
    displayName: 'Setup Test Tools'

#  - script: |
#      source activate BuildEnv
#      ./scripts/ivpm.py update
#      source etc/rv_bfm_env.sh
#      which_conda=`which conda`
#      conda_bindir=`dirname $which_conda`
#      conda_dir=`dirname $conda_bindir`
#      export LD_LIBRARY_PATH=$conda_dir/lib:$LD_LIBRARY_PATH
#      cd ve/rv_out/sim
#      echo "** Running Icarus Verilog Test"
#      runtest.pl -test tests/rv_out_smoke_test.f -sim ivl
#      echo "** Running Verilator Test"
#      runtest.pl -test tests/rv_out_smoke_test.f -sim vlsim +tool.vlsim.tracevcd
#    displayName: 'Run Tests'
  - script: |
      python setup.py bdist_wheel --universal
    displayName: 'Build Wheel'
  - task: TwineAuthenticate@1
    condition: eq(variables['Build.SourceBranchName'], 'master')
    inputs:
      pythonUploadServiceConnection: pypi-vlsim
  - script: |
      # Only deploy from master
      if test "$(Build.SourceBranchName)" = "master"; then
          python -m twine --version
          echo "Calling twine"
          python -m twine upload -r vlsim --config-file $(PYPIRC_PATH) dist/*.whl
          echo "Calling twine complete"
      fi
    displayName: 'Upload to PyPi'
